### PR TITLE
Adding support for quoted record data

### PR DESCRIPTION
**Pull request by donckers**

### CODE REVIEW

**Comment by olof** [comment]
Cool, thanks!

Looks mostly good, but it doesn't handle ; within quoted strings. The following test case would be nice to cover:

```
    dk-singleline2      TXT        "v=DKIM1; descr=singleline; fizz=buzz;"    ; Single line domain key
```

like your dk-singleline, but without the interior `\;`. I made a quick and ugly hack to get the behavior i want (I tested it in bind9 to make sure it behaves like i expect), by effectively excluding the quoted string from further parsing. But it's not the prettiest. In the _parse_zone loop:

```
    for (split /\n/, $zonestr) {
           chomp;

           my @strs = /(".*?(?<!\\)")/g;
           # substitute quoted strings with placeholders
           for my $str (keys @strs) {
                   s/(".*?(?<!\\)")/##STR$str##/;
           }

           s/(?<!\\);.*$//;
           # substitute the placeholders with the real strings again
           for my $str (keys @strs) {
                   s/##STR$str##/$strs[$str]/;
           }
```

Do you have ideas on how to handle this better? Otherwise, maybe my hack could be made to work...

**Comment by donckers** [comment]
Have a look at this commit: https://github.com/donckers/Parse-DNS-Zone/commit/1d855b02e51d64c5c35d0d27cc7c2f04da222a1d

If that is to your liking I'll re-submit a pull request with that code

**Comment by donckers** [comment]
I tested this with a regex substitution as well:

`s/^\s*(?<!\\);.+|\s*(?<!\\);[^"]+?$//g;`

The end result is the same, but the regex is slightly slower (nano-seconds).  Also, it is possible that this regex doesn't account for corner cases like a comment which contains quotes.

My preference is the _strip_comments function, but whatever you like best is what I will submit.

**Comment by olof** [comment]
Hi, sorry for the delay in getting back to you. Was hoping to get some time to dig deeper into it, but haven't yet. I think the _strip_comments is a bit complex, and a regexp soultion would probably be better (the module relies heavily on regular expressions already). Could you adjust to use the regexp? One thing though, it currently doesn't look like it handles quotes in comments, like

```
CNAME something.invalid. ; "foo"
```

Could you verify this (or refute it)? I think getting this right using a single regexp might be tricky. It needs to be able to determine if the comment character is within a quoted string or not.

On the other hand, it's probably still an improvement on the current state of things. I think the module is a bit naive in its design, in hindsight it would probably have been better to normalize and tokenize it properly, and first then interpret it. Would have been way easier to deal with issues like this. And more obvious that support for parts of the zone file format are missing.

**Comment by olof** [comment]
Oh, and by the way: there's no need to open a new pull request, just push to your branch and this pull request gets updated automatically.

**Comment by olof** [comment]
I merged #4, and released it as 0.60. Hope this works for you! Thanks for the patch and report, and sorry for my tardiness etc.

**Pull request closed without merging**
